# Generated by Django 4.1.1 on 2022-10-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_athleteexercise_delete_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteexercise',
            name='exercise_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
