# Generated by Django 4.1.1 on 2022-10-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0003_athleteexercise_exercise_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteexercise',
            name='exercise_time',
        ),
    ]
