# Generated by Django 4.1.1 on 2022-10-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0006_alter_athleteexercise_athlete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteexercise',
            name='athlete',
        ),
        migrations.AddField(
            model_name='athleteexercise',
            name='times',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
