# Generated by Django 4.1.1 on 2022-10-03 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athlete', '0007_remove_athleteexercise_athlete_athleteexercise_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteexercise',
            name='times',
        ),
        migrations.AddField(
            model_name='athleteexercise',
            name='athlete',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
