# Generated by Django 4.1.1 on 2022-10-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0009_alter_athleteexercise_athlete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteexercise',
            name='exercise_date',
            field=models.DateField(auto_now=True),
        ),
    ]
